# create a static PersistentVolume using an existing EBS volume and a Pod that uses it
#We need to ensure that the Pod is scheduled on a node in the same Availability Zone (AZ) as the EBS volume.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: efs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-072a8f44214a23f64 # should be replaced with your EFS volume ID
---
# Create a PersistentVolumeClaim to bind to the static PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: efs-static
  storageClassName: ""
---
# Create a Pod that uses the PersistentVolumeClaim
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    app: efs-static-pod
    project: roboshop
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: efs-volume
# Volume mount name must match the volume name defined below
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-static-claim
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-service
  labels:
    app: efs-static-pod
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    app: efs-static-pod
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80