apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    app: demo
data:
   API_URL: "http://api.example.com"
   LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    app: config-demo
spec:
  containers:
    - name: config-container
      image: nginx
      envFrom:
        - configMapRef:
            name: demo-config