apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  labels:
    app: demo
spec:
  selector:
    app: demo
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
    project: roboshop
    env: dev
spec:
  containers:
    - name: demo-container
      image: nginx
      ports:
        - containerPort: 80