apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
  labels:
     app: multicontainer  
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: almalinux
      command: ["sleep", "1000"]
      